title: Aris Zoleta
# logo: /assets/img/headshot_circle.png
description: Aris Zoleta is pursuing a Ph.D. at DLSU's Graduate School of Economics, with a focus on studying monetary policy, fiscal policy, financial markets, and asset pricing. He is currently employed as a transfer pricing analyst at Cross Border Solution. Before this, he spent 2 years working as a fund accountant at JP Morgan in Manila, and 8 years as an analyst at State Street APAC securities lending business. He also has experience teaching at various universities.
# show_downloads: true
theme: jekyll-theme-minimal
