title: Aris Zoleta
logo: aris-zoleta.github.io/Images/docs
/assets/Pic.jpg
description: Economist with a focus on studying monetary policy, fiscal policy, financial markets, and asset pricing. 
theme: jekyll-theme-minimal
